package com.ahsan.a27smanthademo;


import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.ImageView;
import android.widget.TextView;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import com.backendless.exceptions.BackendlessFault;
import com.ahsan.a27smanthademo.Defaults;

import java.util.HashMap;
import java.util.Map;

public class MainActivity extends AppCompatActivity {



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //Setting up Backendless by following the template I downloaded
        Backendless.setUrl( Defaults.SERVER_URL );  //Get server URL from Defaults.java
        Backendless.initApp( getApplicationContext(), Defaults.APPLICATION_ID, Defaults.API_KEY );

        //In choosePhotoFragment, I want to show image in ImageView instead of dialogue box
        //But right now I don't know if I need to define it here in MainActivity or in ChoosePhotoFragment
        //ImageView imageView = (ImageView) findViewById(R.id.imageView);






        //Check if user is already logged in and launch 2 fragments in MainActivity
        if (Backendless.UserService.loggedInUser() == ""){  //If nobodoy is logged in="" empty string
            //Create MenuFragment to call our fragment from MainActivity
            MenuFragment menuFragment = new MenuFragment();
            getSupportFragmentManager().beginTransaction().add(R.id.container, menuFragment).commit();//Add MenuFragment to container which is activity_main
        } else {
            //Create LoggedinFragment to call our fragment from MainActivity
            LoggedinFragment loggedinFragment = new LoggedinFragment();
            getSupportFragmentManager().beginTransaction().add(R.id.container, loggedinFragment).commit();
        }




/*
        //Now I'm launching AddFriendActivity from list item of LoggedinFragment
        AddFriendFragment addFriendFragment = new AddFriendFragment();
        getSupportFragmentManager().beginTransaction().add(R.id.container, addFriendFragment).commit();

        FriendlistFragment friendlistFragment = new FriendlistFragment();
        getSupportFragmentManager().beginTransaction().add(R.id.friendlistContainer, friendlistFragment).commit();

*/

/*
        //Launch CameraFragment within MainActivity
        CameraFragment cameraFragment = new CameraFragment();
        getSupportFragmentManager().beginTransaction().add(R.id.container, cameraFragment).commit();
*/

        //Choose Photo from gallery fragment
        //ChoosePhotoFragment choosePhotoFragment = new ChoosePhotoFragment();
        //getSupportFragmentManager().beginTransaction().add(R.id.container, choosePhotoFragment).commit();

/*
//==============AutoGenerated Code by App=======================//
        //Create HashMap called testObject
        HashMap testObject = new HashMap<>();

        //foo is column and bar is the value we put in column
        testObject.put( "foo0", "barR" );

        //This line is equavalent to object.saveInBackground() in parse
        Backendless.Data.of( "TestTable" ).save(testObject, new AsyncCallback<Map>() {

            @Override
            public void handleResponse(Map response) {
                TextView label = new TextView(MainActivity.this);//Create TextView and set it's label
                label.setText("Object is saved in Backendless. Please check in the console.");
                setContentView(label);
            }

            @Override
            public void handleFault(BackendlessFault fault) {
                Log.e( "MYAPP", "Server reported an error " + fault.getMessage() );
            }
        });

*/






    }
}

























